# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(blank=True, max_length=200, verbose_name='station')),
                ('min1', models.DateTimeField(blank=True, verbose_name='minutes1')),
                ('min2', models.DateTimeField(blank=True, verbose_name='minutes2')),
            ],
            options={
                'db_table': 'timetable',
                'verbose_name': 'timetable to airport',
            },
        ),
    ]
